events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream service_a {
        server service-a-app:80;
    }

    upstream service_b {
        server service-b-app:80;
    }

    upstream service_c {
        server service-c-nginx:80;
    }

    server {
        listen 80;

        # Service A: Components
        location /api/v1/components {
            proxy_pass http://service_a;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Service A Swagger Docs
        location /api/documentation {
            proxy_pass http://service_a;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Service B: Procurements
        location /api/v1/procurements {
            proxy_pass http://service_b;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Service C: Inbound Shipments
        location /api/v1/inbound-shipments {
            proxy_pass http://service_c;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Fallback
        location / {
            default_type application/json;
            return 404 '{"status": "error", "message": "API Gateway: Route not found"}';
        }
    }
}
