services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: procurement-service-app
        ports:
            - '8001:80'
        volumes:
            - '.:/var/www/html'
        environment:
            DB_CONNECTION: sqlite
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_URL: http://localhost:8001
        networks:
            - backend-network
networks:
    backend-network:
        driver: bridge
